spring:
  datasource:
    url: jdbc:mysql://security-database:3306/security_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: daniel
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    contexts: prod
