spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  liquibase:
    change-log: classpath:db/master.xml
    enabled: false
  sql:
    init:
      mode: never
server:
  address: 0.0.0.0
  port: 8080
