spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
      path: /h2-console
server:
  address: 0.0.0.0
  port: 8080